### ISSUE TITLE
wrong use of libsqlite3 API -- missing 'sqlite3_close' after 'sqlite3_open'

### ISSUE THREAD

**Issue by Zero0one1** [teusbenschop/bibledit-gtk-old#1]
In file 'src/stylesheetutils.cpp', 'sqlite3_close' is missing after 'sqlite3_open', which is needed according to API document.

**Comment by teusbenschop** [comment]
Thank you for finding this issue that can potentially cause problems.

But the code in this repository is marked as old, and it is no longer being maintained.

This code has been forked quite a while ago.
The new repository with this code is at https://github.com/postiffm/bibledit-desktop.
This code is still maintained and in production use.

May you please open this issue there as it likely is relevant there.
