### ISSUE TITLE
Wrongly use SQLite APIs which can cause information leakage and DoS

### ISSUE THREAD

**Issue by Zero0one1** [teusbenschop/bibledit-gtk-old#2]
## 1. missing sqlite3_close() after sqlite3_open()

Hi, developers:

There may be several bugs due to calling  `sqlite3_open(filename, db)` while missing call `sqlite3_close(db)`  after use.

According to [SQLite Documention](https://www.sqlite.org/c3ref/open.html) :

> Whether or not an error occurs when it is opened, resources associated with the [database connection](https://www.sqlite.org/c3ref/sqlite3.html) handle should be released by passing it to [sqlite3_close()](https://www.sqlite.org/c3ref/close.html) when it is no longer required.

Since the connection number of database and resource are limited, if we don't close connection in time, it would leak information and affect process running.

Specific source code locations are below: 

`src/stylesheetutils.cpp:401`

```cpp
396 void stylesheet_set_recently_used(const ustring & stylesheet, vector <ustring>& styles, vector <unsigned int>& counts)
397 {
398   // Connect to db.
399   ustring filename = stylesheet_recent_filename();
400   sqlite3 *db;
401   sqlite3_open(filename.c_str(), &db);
402   char *sql;

```

`src/stylesheetutils.cpp:381`

```cpp
372 void stylesheet_get_recently_used(const ustring & stylesheet, vector <ustring>& markers, vector <unsigned int>& count)
373 // Read the recently used data: markers and usage count.
374 { 
...
380   sqlite3 *db;
381   sqlite3_open(stylesheet_recent_filename().c_str(), &db);
382   sqlite3_busy_timeout(db, 1000);
```

`src/statistics.cpp:95` Before `throw runtime_error` in line 105, 112, 130, it doesn’t close the `db`.

```cpp
 64 void statistics_initial_check_project(const ustring & project, bool gui)
...
 92     sqlite3 *db;
 93     int rc;
 94     try {
 95       rc = sqlite3_open(filename.c_str(), &db);
 96       if (rc)
 97         throw runtime_error(sqlite3_errmsg(db));
 98       char *sql;
```

## 2. missing sqlite3_free() after sqlite3_exec()

There are may be several bugs due to calling  `sqlite3_exec(db, sql, callback, NULL, errmsg)` while missing call `sqlite3_free(errmsg)` after use.

 [SQLite Documention](https://www.sqlite.org/c3ref/exec.html) mentions:

>  If the 5th parameter to sqlite3_exec() is not NULL then any error message is written into memory obtained from [sqlite3_malloc()](https://www.sqlite.org/c3ref/free.html) and passed back through the 5th parameter. To avoid memory leaks, the application should invoke [sqlite3_free()](https://www.sqlite.org/c3ref/free.html)

Otherwise, the memory consumption might be huge, which may become a DoS.

several examples are below: 

`/src/keyterms.cpp:1073`

```cpp
1072     char *sql = g_strdup_printf("delete from renderings where keyword = '%s' and collection = '%s';", double_apostrophy(keyterm).c_str(), double_apostrophy(collection     ).c_str());
1073     rc = sqlite3_exec(db, sql, NULL, NULL, &error);
1074     g_free(sql);
```

`/src/keyterms.cpp:1082`

```cpp
1082       rc = sqlite3_exec(db, sql, NULL, NULL, &error);
1083       g_free(sql);
```

`src/keyterms.cpp:1045`

```cpp
1045     rc = sqlite3_exec(db, sql, reader.callback, &reader, &error);
1046     g_free(sql);
```

There is the whole list of locations related to this problem:

```cmd
src/keyterms.cpp:1073
src/keyterms.cpp:1082
src/keyterms.cpp:1045
src/keyterms.cpp:1018
src/keyterms.cpp:965
src/keyterms.cpp:975
src/keyterms.cpp:984
src/keyterms.cpp:934
src/keyterms.cpp:882
src/keyterms.cpp:904
src/keyterms.cpp:785
src/keyterms.cpp:672
src/keyterms.cpp:680
src/keyterms.cpp:404
src/keyterms.cpp:412
src/keyterms.cpp:306
src/keyterms.cpp:314
src/keyterms.cpp:196
src/keyterms.cpp:204
src/keyterms.cpp:130
src/keyterms.cpp:138
src/kjv.cpp:311
src/kjv.cpp:275
```

**Comment by teusbenschop** [comment]
Thank you for finding this issue that can potentially cause problems.

But the code in this repository is marked as old, and it is no longer being maintained.

This code has been forked quite a while ago.
The new repository with this code is at https://github.com/postiffm/bibledit-desktop.
This code is still maintained and in production use.

May you please open this issue there as it likely is relevant there.
